# Generated by Django 5.1.2 on 2024-11-04 21:57

import app.models.image
import app.models.tag
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from app.migrations.constants import create_admin, create_tags


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[app.models.tag.validate_only_ascii])),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=app.models.image.generate_image_path)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('resolution', models.CharField(max_length=30, validators=[app.models.image.validate_resolution])),
                ('size', models.PositiveIntegerField()),
                ('is_private', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='images', to='app.tag')),
            ],
        ),
        migrations.RunPython(create_admin),
        migrations.RunPython(create_tags),
    ]
