# Generated by Django 5.1.2 on 2024-11-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
